# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CC_TEST_REPORTER_ID: e360f84de7076f58cf70acfc5335d7ddde2232bee661bd6438f2960bdd31be7f
      CODE_CLIMATE_API_URL: https://api.codeclimate.com/v1
      CODE_CLIMATE_API_ORG_NAME: hdamico

    services:
      redis:
        image: redis
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        # Provide the password for postgres
        env:
          PGPORT: 5433
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_password

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Before install
        run: |
            sudo systemctl start postgresql
            psql -c 'create database bicycle_shop;' -U postgres
            psql -U postgres -q -d bicycle_shop -f db/structure.sql
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - name: Install
        run: |
            bundle install
            nvm install node
            node -v
            npm i -g yarn
            yarn
            
      - name: After install
        run: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
